server:
  port: 8888
spring:
  application:
    name: project-gen


gen:
  dirPath: /Users/tangmingjian/Downloads/generated
  templatesPath: /Users/tangmingjian/IdeaProjects/project-gen/src/main/resources/tpls/gasdf

